### ISSUE TITLE
`aminoAcidToDegenerateDnaMap.js` is using a RNA map for converting AA sequence to DNA sequence

### ISSUE THREAD

**Issue by XingGao-PKI** [TeselaGen/ve-sequence-utils#195]
Hi @tnrich, 
I found the `Copy DNA BPs` functionality is not working correctly, then I did some dig up, found the `aminoAcidToDegenerateDnaMap.js` file is using a RNA map parsing AA seq to DNA seq. (Should change all `u` to `t`). This is not right, could you fix this ?

Also, the `R` amnio acid should be `mgn`, rather than `mng`, could you also fix this? 

Or may I submit a PR instead ?

@tnrich

**Comment by tnrich** [comment]
I'd love if you submitted a PR with any appropriate tests! Thanks for looking into this @XingGao-PKI

**Comment by XingGao-PKI** [comment]
Fixed in #196
