### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by udp** [TeselaGen/ve-sequence-utils#2]
There's no license file attached and the package.json says "ISC", which is the "npm init" default.  If it is ISC that is fine, but it would be nice if this was clarified in a LICENSE file.

**Comment by mfero** [comment]
Hi James,

Thomas will fix that problem. Thanks for pointing it out! He will also reach out to be sure we get you looped into the current developments on Open VE. The code base may be in flux as we upgrade/integrate the open source version into our enterprise tool and ease out the older version. Any and all suggestions are very welcome.

Cheers,

Mike

Michael Fero PhD
CEO, TeselaGen Biotechnology, Inc.
phone: 650-387-5932 | email: mike.fero@teselagen.com
Confidentiality Notice:  This e-mail message, including all attachments, is for the sole use of the intended recipient(s) and may contain confidential, proprietary, and/or privileged information protected by law. If you are not the intended recipient, you may not use, copy, or distribute this restricted e-mail message or its attachments.  If you believe you have received this e-mail message in error, please contact the sender by replying to this e-mail and destroy all copies of the original message.

**Comment by mfero** [comment]
Hi James,

I'm a developer with Teselagen. I just added a LICENSE file to
ve-sequence-utils and our other associated repos (ve-sequence-parsers,
ve-range-utils, teselagen-react-components).

Please let me know if you have any questions at all about using our tools
or any feature requests you might have.

-Thomas

**Comment by udp** [comment]
That's great, thank you very much!  Looking forward to making use of this.  It's exciting to see how quickly JS is gaining library support in the bioinformatics space. 🙂

James
