### ISSUE TITLE
Add 'U' to proteinAlphabet.js

### ISSUE THREAD

**Issue by solenevEPAM** [TeselaGen/ve-sequence-utils#5]
There is **U** letter which is missing in [_proteinAlphabet.js_](https://github.com/TeselaGen/ve-sequence-utils/blob/master/src/proteinAlphabet.js)
**U** exists is in the FASTA format ([Wiki](https://en.wikipedia.org/wiki/FASTA_format), [NCBI](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp))

Change: add field **U** in exported object with following fields. 
```
U: {
    value: "U",
    name: "Selenocysteine",
    threeLettersName: "Sec",
    hydrophobicity: ?,
    color: "#??????"
  }
```
However, I couldn't find any info on _hydrophobicity_ for Selenocysteine 
and I am not familiar with your coloring system 

https://en.wikipedia.org/wiki/Selenocysteine

**Comment by tnrich** [comment]
Hey @solenevEPAM!  

Sorry for the delay in getting back to you! I just made a new issue template that mentions me (@tnrich) directly so I should get email notifications in the future. 


I've gone ahead and added Selenocysteine to the AA list. I didn't add a hydrophobicity but if we figure out what that value is we can add it later. 

https://github.com/TeselaGen/ve-sequence-utils/commit/2bdb0301dc0d76ebbe9f62ca5122420c5b0430be

**Comment by solenevEPAM** [comment]
Hi @tnrich !

Thank you for the update! I've tried with a new version and found out that there are a few more changes needed: 

1. I've updated filterAminoAcidSequenceString in ve-sequence-utils: added **u** there, so fasta files are parsed successfully.
2. And updated an error message in ve-sequence-parsers. It was a bit outdated.

You could find links to the pull requests above.

Please, let me know if there are any problems with them.

**Comment by tnrich** [comment]
@solenevEPAM I believe I've fixed these. Lemme know if it is solved for you and I'll close this issue.

**Comment by solenevEPAM** [comment]
@tnrich 
Yes, have tested master - works OK (however had to make these changes in the 'lib' folder manually)
Could you, please, publish a new version with these changes?

**Comment by solenevEPAM** [comment]
Have tested new versions of **ve-sequence-parsers** and **ve-sequence-utils** works fine.
Thank you!
